### ISSUE TITLE
function to next() returns promise

### ISSUE THREAD

**Issue by robshep** [ifavo/espruino-modules#1]
Hi Mario,

Thanks for creating promises for Espruino!

I'm trying to write a chain where the call inside next() returns a promise.

It is the promise that is delivered to the next().next(promise)  and not the resolved object

next().next(promise.resolved)

Please consider this example

```
testSuccess().then(function () {
    return "success1";

}).next(function(input) {
    console.log(input); // called after 2000ms.
    return testSuccess().then(function(){
        return "success2"
    });
}, null, 2000).next(function(res) {
    console.log(res); // call after more 2000ms, and res is "ok"
}, null, 2000);
```

The output is

```
success1
{ state_: 'resolved',
  chain_: [],
  scope_: null,
  result_: 'success2' }
```

how could It be tweaked to perform the resolution in the chain so we get

```
success1
success2
```

**Comment by ifavo** [comment]
Hi Rob,

the easiest way would be to just pass the first result to the next one, like this:

```
testSuccess().then(function () {
    return "success1";

}).next(function(input) {
    console.log(input); // called after 2000ms.
    return testSuccess().then(function(){
        return [input, "success2"]; /* return an array with both results here instead of just a string */
    });
}, null, 2000).next(function(res) {
    console.log(res); // call after more 2000ms, and res is "ok"
}, null, 2000);
```

This will create an array with `input` & `success2` which is then passed on to the next function.

Is this what you are looking for?

Cheers,
 Mario
